---
title: "Descriptives by Group"
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(viridis)
library(RColorBrewer)

plot_question_bar <- function(dat) {
  ggplot(data = dat,
         aes(x = stringr::str_wrap(response, 60),
             y = n,
             fill=as.factor(group5))
  ) +
    geom_bar(stat = "identity",
             position = "dodge2") +
    xlab("") +
    ylab("Count") +
    scale_fill_manual(name = "Cluster",
                      values = .GlobalEnv$COLORS) +
    #labels(line_break(dat$response)) +
    coord_flip() +
    ggtitle(stringr::str_wrap(dat$question_text, 80)) +
    theme_minimal() +
    theme(
      plot.title.position = "plot",
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(colour = "black")
      
    )
}

fs::dir_create(here("./output", "persona", "group_descriptives_5"), recurse = TRUE)


# generated from clustering.Rmd
persona <- readr::read_tsv(here("./data/final/persona/persona_group_5.tsv"))
metadata <- jsonlite::read_json(here("./data/original/surveys/02-self_assessment_metadata.json"))

counts <- persona %>%
  dplyr::group_by(group5, qbase, question_text) %>%
  dplyr::count(response) %>%
  tidyr::drop_na() %>%
  dplyr::ungroup()
```

# Question Bar Graphs

```{r}
brewer.pal(8, "Dark2")
display.brewer.pal(8, "Dark2")
COLORS <- brewer.pal(8, "Dark2")[c(1:4, 6)]
```


```{r}
for (q in unique(counts$qbase)) {
  print(q)
  if (q %in% c("Q7.2", "Q7.3", "Q7.4")) {next}

  g <- plot_question_bar(dplyr::filter(counts, qbase == q))
  pth <- here("./output", "persona", "group_descriptives_5", glue::glue("{q}.png"))
  #print(pth)
  print(g)
  ggsave(filename = pth, plot = g, width = 8, height = 5, units = "in")
  #break
}
```

# Likert table

```{r, fig.width=8, fig.height=5}
likert <- persona %>%
  dplyr::filter(qbase == "Q7.2")

likert_questions5 <- metadata[["questions"]][["QID19"]][["subQuestions"]] %>%
  purrr::map(magrittr::extract2, "choiceText") %>%
  purrr::map_chr(magrittr::extract2, 1) %>%
  tibble::tibble(text = .) %>%
  dplyr::mutate(part = rownames(.)) %>%
  dplyr::mutate(question_part = paste0("Q7.2_", part)) %>%
  dplyr::full_join(likert, by = c("question_part")) %>%
  dplyr::select(id, group5, qbase, qid, text, response)

```

## Heatmap

```{r}
likert_q_count5 <- likert_questions5 %>%
  dplyr::group_by(group5, text) %>%
  dplyr::count(response) %>%
  dplyr::filter(!is.na(group5))
```


```{r}
#table(likert_questions$text, likert_questions$response)
```

```{r, fig.width=13, fig.height=8}

# word wrap and re-order the x axis before plotting
x_wrap_len <- 10
x_levels <- stringr::str_wrap(c(NA,
                                "Strongly Disagree", "Disagree", "Somewhat Disagree",
                                "Neither Agree nor Disagree",
                                "Somewhat Agree", "Agree", "Strongly Agree"),
                              x_wrap_len)
x_factor <- factor(stringr::str_wrap(likert_q_count5$response, x_wrap_len),
                   levels = x_levels)

g <- ggplot(likert_q_count5,
       aes(x = x_factor,
           y = stringr::str_wrap(text, 50))) +
  geom_tile(aes(fill = n)) +
  geom_text(aes(label = n)) +
  facet_wrap(~ group5) +
  scale_fill_viridis() +
  xlab("") +
  ylab("") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 1)) +
  NULL
print(g)
```

```{r}
ggsave(filename = here("./output", "persona", "group_descriptives_5", "likert.png"),
       plot = g,
       width = 13,
       height = 8,
       units = "in")
```

# Free Response

- Q7.3: Please share what you most hope to learn from participating in this workshop and/or workshop series. 
- Q7.4: What do you want to know or be able to do after this workshop (or series of sessions) that you don't know or can't do right now?

## Paired responses by group


```{r}
reponse_table <- persona %>%
  dplyr::filter(qbase == "Q7.3" | qbase == "Q7.4") %>%
  dplyr::select(group5, id, qbase, response) %>%
  tidyr::pivot_wider(names_from = qbase, values_from = response) %>%
  dplyr::filter(! (is.na(Q7.3) & is.na(Q7.4))) %>%
  dplyr::arrange(group5, id)

reponse_table %>%
  knitr::kable() %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
  row_spec(which(reponse_table$group5 == 1), color = "white", background = .GlobalEnv$COLORS[1]) %>%
  row_spec(which(reponse_table$group5 == 2), color = "white", background = .GlobalEnv$COLORS[2]) %>%
  row_spec(which(reponse_table$group5 == 3), color = "white", background = .GlobalEnv$COLORS[3]) %>%
  row_spec(which(reponse_table$group5 == 4), color = "white", background = .GlobalEnv$COLORS[4]) %>%
  row_spec(which(reponse_table$group5 == 5), color = "white", background = .GlobalEnv$COLORS[5])
  
```
