---
title: "Self-Assessment Descriptives"
output: 
  html_document: 
    toc: yes
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE}
library(here)
library(readr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(fs)
library(stringi)
library(knitr)
library(kableExtra)
library(viridis)


plot_question_bar <- function(dat) {
  ggplot(data = dat,
         aes(x = stringr::str_wrap(response, 60),
             y = n)
  ) +
    geom_bar(stat="identity") +
    xlab("") +
    ylab("Count") +
    #labels(line_break(dat$response)) +
    coord_flip() +
    ggtitle(stringr::str_wrap(dat$question_text, 100)) +
    theme_minimal() +
    theme(
      plot.title.position = "plot"
    )
}

metadata <- jsonlite::read_json(here("./data/original/surveys/02-self_assessment_metadata.json"))
persona <- readr::read_tsv(here("./data/original/surveys/02-self_assessment_with_questions.tsv"))

counts <- persona %>%
  dplyr::group_by(qbase, question_text) %>%
  dplyr::count(response) %>%
  tidyr::drop_na()
```

```{r}
# plot_question_bar(dplyr::filter(counts, qbase==unique(counts$qbase)[[11]]))
```

# Question Bar Graphs

```{r, fig.width=8, fig.height=5}
fs::dir_create(here("./output", "survey", "01-self_assessment"), recurse = TRUE)

for (q in unique(counts$qbase)) {
  print(q)
  g <- plot_question_bar(dplyr::filter(counts, qbase==q))
  pth <- here("./output", "survey", "01-self_assessment", glue::glue("{q}.png"))
  #print(pth)
  print(g)
  ggsave(filename = pth, plot = g, width = 8, height = 5, units = "in")
}
```

# Likert table

```{r, fig.width=8, fig.height=5}
likert <- persona %>%
  dplyr::filter(qbase == "Q7.2")

likert_questions <- metadata[["questions"]][["QID19"]][["subQuestions"]] %>%
  purrr::map(magrittr::extract2, "choiceText") %>%
  purrr::map_chr(magrittr::extract2, 1) %>%
  tibble::tibble(text = .) %>%
  dplyr::mutate(part = rownames(.)) %>%
  dplyr::mutate(question_part = paste0("Q7.2_", part)) %>%
  dplyr::full_join(likert, by = c("question_part")) %>%
  dplyr::select(id, qbase, qid, text, response)

```

## Heatmap

```{r}
likert_q_count <- likert_questions %>%
  dplyr::group_by(text) %>%
  dplyr::count(response)
```


```{r}
#table(likert_questions$text, likert_questions$response)
```

```{r, fig.width=8, fig.height=5}

# word wrap and re-order the x axis before plotting
x_wrap_len <- 10
x_levels <- stringr::str_wrap(c(NA,
                                "Strongly Disagree", "Disagree", "Somewhat Disagree",
                                "Neither Agree nor Disagree",
                                "Somewhat Agree", "Agree", "Strongly Agree"),
                              x_wrap_len)
x_factor <- factor(stringr::str_wrap(likert_q_count$response, x_wrap_len),
                   levels = x_levels)

g <- ggplot(likert_q_count,
       aes(x = x_factor,
           y = stringr::str_wrap(text, 50))) +
  geom_tile(aes(fill = n)) +
  geom_text(aes(label = n)) +
  scale_fill_viridis() +
  xlab("") +
  ylab("") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0, vjust = 1))
  NULL
print(g)
```

```{r}
ggsave(filename = here("./output", "survey", "01-self_assessment", "likert.png"),
       plot = g,
       width = 8,
       height = 5,
       units = "in")
```



# Free Response

- Q7.3: Please share what you most hope to learn from participating in this workshop and/or workshop series. 
- Q7.4: What do you want to know or be able to do after this workshop (or series of sessions) that you don't know or can't do right now?

## Paired responses

```{r}
persona %>%
  dplyr::filter(qbase == "Q7.3" | qbase == "Q7.4") %>%
  dplyr::select(id, qbase, response) %>%
  tidyr::pivot_wider(names_from = qbase, values_from = response) %>%
  dplyr::filter(! (is.na(Q7.3) & is.na(Q7.4))) %>%
  knitr::kable() %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
  
```


## All responses

```{r}
persona %>%
  dplyr::filter(qbase == "Q7.3") %>%
  dplyr::select(response) %>%
  tidyr::drop_na() %>%
  dplyr::pull(1)
```

```{r}
persona %>%
  dplyr::filter(qbase == "Q7.4") %>%
  dplyr::select(response) %>%
  tidyr::drop_na() %>%
  dplyr::pull(1)
```