---
title: "Self-Assessment Descriptives"
output: 
  html_document: 
    toc: yes
    number_sections: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message=FALSE}
library(here)
library(readr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(fs)
library(stringi)
library(knitr)
library(kableExtra)
library(viridis)
library(glue)
library(forcats)

source(here("./R/plot_question_bar.R"))
source(here("./R/likert.R"))
source(here("./R/recode_occupation.R"))
source(here("./R/save_analysis_edt.R"))

metadata <- jsonlite::read_json(here("./data/final/01-surveys/01-self_assessment_persona_metadata.json"))
persona <- readr::read_tsv(here("./data/final/01-surveys/01-self_assessment_persona_with_questions.tsv"))

stopifnot(nrow(persona) == 4690)

counts <- persona %>%
  dplyr::group_by(qbase, question_text) %>%
  dplyr::count(response) %>%
  dplyr::ungroup() %>%
  tidyr::drop_na()
```

```{r}
# plot_question_bar(dplyr::filter(counts, qbase==unique(counts$qbase)[[11]]))
```

## Other responses

```{r}
text_responses <- persona %>%
  dplyr::filter(stringr::str_detect(question_part, "TEXT")) %>%
  tidyr::drop_na() %>%
  group_by(question_part) %>%
  count(response)

text_responses %>%
  dplyr::arrange(question_part, -n) %>%
  print(n = Inf)
```

## Counts

```{r}
# num unique responses
num_respondents <- persona$id_person %>%
  unique() %>%
  .[!is.na(.)] %>%
  length()
num_respondents
```

```{r}
num_consented_df <- persona %>%
  dplyr::filter(question_part %in% c("Q1.3", "Q1.4")) %>%
  dplyr::select(id_person, id_response, question_part, response) %>%
  #dplyr::group_by(id_person, question_part) %>%
  #dplyr::filter(row_number() == 1) %>% # selects only the first entry
  {.}

stopifnot(all(table(num_consented_df$id_person) == 2)) # this is also a duplicate ID check

num_consented_df <- num_consented_df %>%
  tidyr::pivot_wider(names_from = question_part,
                     values_from = response) %>%
  dplyr::mutate(
    qualify = dplyr::case_when(
      stringr::str_starts(Q1.3, "Yes") & stringr::str_starts(Q1.4, "Yes") ~ TRUE,
      TRUE ~ FALSE
    )
  )


stopifnot(any(duplicated(num_consented_df$id_person)) == FALSE)

table(num_consented_df$qualify)

num_consented <- length(num_consented_df$id_person)
```

```{r}
glue::glue("Number of consented reponses: {num_consented}")
```


```{r}
persona %>%
  dplyr::filter(is.na(id_person))
```

## Grouped Demographics

```{r}
occuptation_choices <- purrr::map(metadata$questions$QID2$choices,
                                      ~ magrittr::extract2(., "choiceText")) %>%
  unlist()
```

```{r}
counts %>%
  dplyr::filter(qbase == "Q2.3") %>%
  dplyr::pull(response)
```

```{r}
occupation <- counts %>%
  dplyr::filter(qbase == "Q2.3") %>%
  recode_occupation(response)
```

```{r}
# make sure the "other" counts are equal to sum of the text responses
num_groups_created <- occupation %>%
  dplyr::filter(!response %in% occuptation_choices) %>%
  pull(n) %>%
  sum()

num_other_responses <- occupation %>%
              dplyr::filter(
                response == "Other, please describe"
              ) %>%
              pull(n)

stopifnot(num_groups_created + 1 == num_other_responses) # adding 1 because i'm not counting "other"
```

```{r}
occupation <- occupation %>%
  tidyr::drop_na()
```

```{r}
# check the groups were all binned correctly
table(occupation$response, occupation$occupation_group, useNA = "always") %>% addmargins()
```

```{r}
total_occupation_counts <- occupation$n %>% sum()
total_occupation_counts
```

```{r}
occupation %>% group_by(occupation_group) %>% summarize(ct = sum(n))
```

```{r}
fs::dir_create(here("./output", "survey", "01-self_assessment"), recurse = TRUE)
```


```{r}
g <- ggplot(data = occupation, aes(x = forcats::fct_reorder(occupation_group, n), y = n)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  coord_flip() +
  labs(title = "Occupation Counts",
       subtitle = glue::glue("n = {num_consented}, responses={total_occupation_counts}")) +
  theme(text = element_text(size=20),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
        )

print(g)

save_analysis_edt(
  g = g,
  analysis_pth = here::here("./output", "survey", "01-self_assessment", "grouped_demographics.png"),
  edt_pth = here::here("../", "dissertation-edt", "figs", "020-persona", "grouped_demographics.png"),
  width = 5, height = 3, units = "in", bg = "white"
)
```

# Question Bar Graphs

```{r, fig.width=8, fig.height=5}
for (q in unique(counts$qbase)) {
  #print(q)
  if (q %in% c("Q7.2", "Q7.3", "Q7.4")) {next} # skip the likert and free-response questions for later
  
 
  if (q %in% c("Q2.3")) {  # order by count
    type <- "by_count"
  } else if (q %in% c()) { # order by likert
    type <- "by_likert"
  } else {
    type = "asis"
  }

  g <- plot_question_bar(dplyr::filter(counts, qbase == q), type = type)
  pth <- here("./output", "survey", "01-self_assessment", glue::glue("{q}.png"))
  #print(pth)
  print(g)
  
  if (q %in% c("Q2.3")) { # plots used for dissertation
    edt_pth <- here("..",
              "dissertation-edt",
              "figs",
              "020-persona",
              glue::glue("{q}.png"))
    save_analysis_edt(
      g = g,
      analysis_pth = pth,
      edt_pth = edt_pth,
      width = 8, height = 5, units = "in", bg = "white"
    )
  } else {
    ggsave(filename = pth, plot = g, width = 8, height = 5, units = "in", bg = "white")
  }
}
```

# Likert table

```{r, fig.width=8, fig.height=5}
qbase <- "Q7.2"
qid <- get_qid_from_qbase(persona, qbase)
qid

likert_q_count <- likert_calculation(persona, metadata, qbase, qid)
g <- likert_plot(likert_q_count %>% tidyr::drop_na())
g
```

```{r}
save_analysis_edt(
  g = g,
  analysis_pth = here("./output", "survey", "01-self_assessment", "likert.png"),
  edt_pth = here("../", "dissertation-edt", "figs", "020-persona", "likert.png"),
  width = 8,
  height = 5,
  units = "in",
  bg = "white"
)
```


```{r}
ggsave(filename = here("./output", "survey", "01-self_assessment", "likert.png"),
       plot = g,
       width = 8,
       height = 5,
       units = "in")
```



# Free Response

- Q7.3: Please share what you most hope to learn from participating in this workshop and/or workshop series. 
- Q7.4: What do you want to know or be able to do after this workshop (or series of sessions) that you don't know or can't do right now?

## Paired responses

```{r}
persona %>%
  dplyr::filter(qbase == "Q7.3" | qbase == "Q7.4") %>%
  dplyr::select(id_person, qbase, response) %>%
  tidyr::pivot_wider(names_from = qbase, values_from = response) %>%
  dplyr::filter(! (is.na(Q7.3) & is.na(Q7.4))) %>%
  knitr::kable() %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
  
```


## All responses

```{r}
persona %>%
  dplyr::filter(qbase == "Q7.3") %>%
  dplyr::select(response) %>%
  tidyr::drop_na() %>%
  dplyr::pull(1)
```

```{r}
persona %>%
  dplyr::filter(qbase == "Q7.4") %>%
  dplyr::select(response) %>%
  tidyr::drop_na() %>%
  dplyr::pull(1)
```
